extends SceneTree
## Writes down what Godot's OWN font can already draw.
##
## The web build has no operating system to ask for a face, so SystemFont
## resolves to nothing and rendering falls through to the engine's built-in
## font. That face is compiled into the binary and is therefore identical on
## every platform, which is what makes this list safe to commit.
##
## build-font-subset.py subtracts this from the set it demands. Without it the
## gate insists the Japanese subset also carry Latin Extended-A — glyphs the
## engine already has — and a false failure there costs more than the bytes: it
## once made me rename a character rather than trust the font.
##
##     godot --headless --path . --script tools/dump-builtin-font-coverage.gd

func _init() -> void:
	var f := ThemeDB.fallback_font
	var covered: PackedInt32Array = []
	# Latin, Latin-1, Latin Extended-A/B, punctuation, symbols and arrows. Not
	# CJK: the engine has none, which is the whole reason the subset exists.
	for cp in range(0x20, 0x2C00):
		if f.has_char(cp):
			covered.append(cp)
	var out := FileAccess.open("res://tools/builtin-font-coverage.txt", FileAccess.WRITE)
	out.store_line("# Generated by tools/dump-builtin-font-coverage.gd — do not hand-edit.")
	out.store_line("# Codepoints Godot's built-in font can already draw, so the bundled")
	out.store_line("# subset does not need to carry them. Regenerate after a Godot bump.")
	out.store_line("# godot version: %s" % Engine.get_version_info()["string"])
	for cp in covered:
		out.store_line("%04X" % cp)
	out.close()
	print("wrote %d codepoints" % covered.size())
	quit(0)
