// stage-contact.mjs — every 2D stage plate with the canonical arena drawn on it.
//
// STAGE_SPEC.md says the grid is the fixed thing and a stage is art produced to
// sit under it. That is a claim about each plate that can only be settled by
// LOOKING: a gate can tell you a file exists and is 1920x1080, it cannot tell
// you whether the crates are standing inside the diamond. So this emits one
// sheet with the arena drawn over every plate at once, which is the cheapest
// way to see which locations hold the board and which do not.
//
// It reads ARENA out of formation_battle.gd exactly as stage-template.mjs does,
// for the same reason: a template that disagrees with the engine is worse than
// no template.
//
//   node godot/tools/stage-contact.mjs > stage-contact.svg
//   node godot/tools/stage-contact.mjs --cols 3 > stage-contact.svg
//
// The plates are referenced, not embedded, so the SVG must sit at the repo root
// (its hrefs are repo-relative). Open it in a browser.
//
// Reading it: BLUE is where units stand. AMBER DASHED is the 1.22x floor
// margin — ground must still be there, because a figure draws upward from its
// feet and the back rank stands on the outer cells. The darkened band is the
// command console, which is covered in play, so anything composed there is
// wasted rather than wrong.

import { readFileSync, readdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../..');
const src = readFileSync(resolve(here, '../scenes/formation_battle.gd'), 'utf8');

function num(re, label) {
  const m = src.match(re);
  if (!m) {
    console.error(`stage-contact: could not read ${label} from formation_battle.gd`);
    process.exit(1);
  }
  return parseFloat(m[1]);
}

const cx = num(/const ARENA := \{"c": Vector2\(([\d.]+),/, 'arena centre x');
const cy = num(/const ARENA := \{"c": Vector2\([\d.]+,\s*([\d.]+)\)/, 'arena centre y');
const fwd = num(/const ARENA := .*"fwd":\s*([\d.]+)/, 'arena fwd');
const lane = num(/const ARENA := .*"lane":\s*([\d.]+)/, 'arena lane');
const FWD = num(/const FORWARD := Vector2\(([-\d.]+),/, 'FORWARD.x');
const FWDY = num(/const FORWARD := Vector2\([-\d.]+,\s*([-\d.]+)\)/, 'FORWARD.y');
const LANX = num(/const LANE_AXIS := Vector2\(([-\d.]+),/, 'LANE_AXIS.x');
const LANY = num(/const LANE_AXIS := Vector2\([-\d.]+,\s*([-\d.]+)\)/, 'LANE_AXIS.y');

// One cell of the sheet is a whole 16:9 frame, scaled down. Every proportion
// below is a fraction of the frame, so the arena lands correctly at any size.
const W = 640, H = Math.round((W * 9) / 16);
const CONSOLE = (188 / 768) * H;
const PLATE_H = H - CONSOLE;
const MARGIN = 1.22;

const c = { x: cx * W, y: cy * PLATE_H };
const f = { x: FWD * fwd * W, y: FWDY * fwd * W };
const l = { x: LANX * lane * W, y: LANY * lane * W };
const pt = (sf, sl, k = 1) =>
  `${(c.x + k * sf * f.x + k * sl * l.x).toFixed(1)},${(c.y + k * sf * f.y + k * sl * l.y).toFixed(1)}`;
const arena = [pt(-1, -1), pt(1, -1), pt(1, 1), pt(-1, 1)].join(' ');
const floor = [pt(-1, -1, MARGIN), pt(1, -1, MARGIN), pt(1, 1, MARGIN), pt(-1, 1, MARGIN)].join(' ');

const SCENES = 'art/v3/scenes';
const plates = readdirSync(resolve(repo, SCENES)).filter(n => n.endsWith('.webp')).sort();

if (process.argv.includes('--check')) {
  console.log(`CONTACT OK: arena centre ${cx},${cy} fwd ${fwd} lane ${lane}, ${plates.length} plates`);
  process.exit(0);
}

const ci = process.argv.indexOf('--cols');
const COLS = ci > -1 ? Math.max(1, parseInt(process.argv[ci + 1], 10) || 2) : 2;
const GAP = 18, CAP = 26, HEAD = 96;
const rows = Math.ceil(plates.length / COLS);
const SW = COLS * W + (COLS + 1) * GAP;
const SH = HEAD + rows * (H + CAP + GAP) + GAP;

const cells = plates.map((name, i) => {
  const x = GAP + (i % COLS) * (W + GAP);
  const y = HEAD + Math.floor(i / COLS) * (H + CAP + GAP);
  return `  <g transform="translate(${x},${y})">
    <image href="${SCENES}/${name}" x="0" y="0" width="${W}" height="${H}"/>
    <rect x="0" y="${PLATE_H.toFixed(1)}" width="${W}" height="${CONSOLE.toFixed(1)}" fill="#000" opacity="0.55"/>
    <polygon points="${floor}" fill="none" stroke="#ffb020" stroke-width="2" stroke-dasharray="7 6"/>
    <polygon points="${arena}" fill="#4da6ff" fill-opacity="0.16" stroke="#4da6ff" stroke-width="2.5"/>
    <rect x="0" y="0" width="${W}" height="${H}" fill="none" stroke="#2b3138"/>
    <text x="2" y="${H + 18}" font-family="monospace" font-size="14" fill="#8d8165">${name.replace(/\.webp$/, '')}</text>
  </g>`;
}).join('\n');

process.stdout.write(`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     width="${SW}" height="${SH}" viewBox="0 0 ${SW} ${SH}">
  <!-- Generated by godot/tools/stage-contact.mjs. Keep this file at the repo
       root: the plate hrefs are repo-relative. -->
  <rect width="${SW}" height="${SH}" fill="#15181c"/>
  <text x="${GAP}" y="34" font-family="monospace" font-size="19" fill="#8faf6a">${SCENES} — the canonical arena drawn on each plate</text>
  <text x="${GAP}" y="60" font-family="monospace" font-size="14" fill="#8d8165">blue = where units stand (formation_battle.gd ARENA) · amber dashed = the ${MARGIN}x floor margin, ground must still be there</text>
  <text x="${GAP}" y="80" font-family="monospace" font-size="14" fill="#8d8165">darkened band = the command console, covered in play · STAGE_SPEC.md 1-2 is what each plate is being judged against</text>
${cells}
</svg>
`);
