#!/usr/bin/env node
/**
 * The mission gate. Bare node, no browser — so it runs on every edit.
 *
 *   node missions/test/model.mjs
 *
 * It checks the claims MISSIONS.md makes, and it also runs the FOUR AUTHORED
 * MISSIONS in the slice through the validator. That second half is the point:
 * a model that only ever sees its own fixtures is a model that agrees with
 * itself. §6's table is generated by this file rather than remembered.
 */
import { readFileSync } from 'node:fs';
import { cost, validate, fire, VERBS, TRIGGERS, BLOCK_MINUTES, REAL_BUDGET } from '../model.mjs';
import { exposure } from '../../market/model.mjs';

const slice = JSON.parse(readFileSync(new URL('../../content/era1-slice-v1.json', import.meta.url)));
const board = JSON.parse(readFileSync(new URL('../../map/kallio-era1-2003-v1.json', import.meta.url)));
const anchor = id => board.anchors.find(a => a.id === id) ?? board.anchors[0];

let pass = 0, fail = 0;
const ok = (cond, what) => { if (cond) { pass++; } else { fail++; console.log('  FAIL  ' + what); } };

// A mission that is everything §1 asks for, to test against.
const GOOD = {
  id: 'test-good',
  signal_encounter_id: 'enc-toko-quiet-voice',
  deadline: { day: 5, block: 'night' },
  steps: [
    { verb: 'MEET', anchor: 'vaasankatu', alternatives: ['send a crew member'] },
    { verb: 'MOVE', anchor: 'harju', alternatives: ['walk it'], triggers: ['smell', 'bulk'] },
    { verb: 'SELL', anchor: 'harju', alternatives: ['split the load'], triggers: ['dry'] },
    { verb: 'LOSE', anchor: 'siltasaari', alternatives: ['go to ground'] },
  ],
  success_effects: ['flag:van-pattern', 'rapport:toko:+1'],
  partial_effects: ['pressure:harju:+1'],
  failure_effects: ['relationship:toko:-1'],
};

// ── 1. the clock ────────────────────────────────────────────────────────────
{
  const c = cost(GOOD);
  ok(c.fitsBlock, `a four-step mission fits one block (${c.igm} of ${BLOCK_MINUTES} minutes)`);
  ok(c.fitsReal, `and fits the real budget (~${c.real} of ${REAL_BUDGET.max} minutes)`);
  ok(!c.thin, 'and is not thin');

  // §2.2's own arithmetic: about two minutes a step.
  const per = c.real / c.steps;
  ok(per > 1.0 && per < 3.0, `a step averages ~${per.toFixed(1)} real minutes`);

  // The block is the ceiling and it must actually bite.
  const long = { ...GOOD, steps: Array.from({ length: 9 }, () => ({ verb: 'SELL', anchor: 'harju', alternatives: ['x'] })) };
  const lc = cost(long);
  ok(!lc.fitsBlock, 'nine selling stops do NOT fit a block — the ceiling is real');
  ok(!lc.fitsReal, 'and would not fit the real budget either');

  // Both currencies must be able to fail INDEPENDENTLY, or one of them is
  // decoration. HOLD is cheap to play and expensive to live through.
  const idle = { ...GOOD, steps: Array.from({ length: 5 }, () => ({ verb: 'HOLD', anchor: 'harju', alternatives: ['x'] })) };
  const ic = cost(idle);
  ok(!ic.fitsBlock && ic.fitsReal, 'a mission can be too long to HAPPEN while still quick to PLAY');
}

// ── 2. validate reports what is missing, not just that something is ─────────
{
  const v = validate(GOOD);
  ok(v.ok, `a complete mission validates (${v.findings.length} note(s))`);

  const noSteps = { ...GOOD, steps: [] };
  const nv = validate(noSteps);
  ok(!nv.ok && nv.findings.some(f => /errand/.test(f.what)), 'a mission with no steps is named as an errand');

  const twoOutcomes = { ...GOOD, partial_effects: [] };
  ok(!validate(twoOutcomes).ok, '§1: two outcomes is a test, not a story');

  const cashOnly = { ...GOOD, success_effects: ['cash:2400'] };
  ok(!validate(cashOnly).ok, '§5: a mission paying only cash is rejected');

  const oneRoom = { ...GOOD, steps: GOOD.steps.map(s => ({ ...s, anchor: 'harju' })) };
  ok(validate(oneRoom).findings.some(f => /same place/.test(f.what)), 'all-in-one-place is flagged');

  const noAlt = { ...GOOD, steps: GOOD.steps.map(s => ({ ...s, alternatives: [] })) };
  ok(validate(noAlt).findings.some(f => /corridor/.test(f.what)), '§3: a step with no alternative is a corridor');

  const badVerb = { ...GOOD, steps: [{ verb: 'SNEAK', anchor: 'harju', alternatives: ['x'] }] };
  ok(!validate(badVerb).ok, 'an unknown verb is an error, not a shrug');
}

// ── 3. triggers fire, and the answer spends them ───────────────────────────
{
  const step = { verb: 'MOVE', triggers: ['smell'] };
  const base = { anchor: anchor('piritori'), carrying: ['weed'], transport: 'public', block: 'day', busy: true, units: 3 };

  const bare = fire(step, base, exposure);
  ok(bare.fired.length === 1 && !bare.fired[0].answered, 'weed on a tram fires `smell`');
  ok(bare.fired[0].band, `and exposure supplies the severity (${bare.fired[0].band})`);

  const packed = fire(step, { ...base, kit: ['carbon-bag'] }, exposure);
  ok(packed.fired.length === 1 && packed.fired[0].answered, 'a carbon-lined bag answers it — it still FIRES');
  ok(/nothing came of it/.test(packed.fired[0].text), 'and the player is told the bag worked');
  ok(packed.fired[0].band === null, 'an answered trigger costs nothing');

  const walking = fire(step, { ...base, transport: 'foot' }, exposure);
  ok(walking.clean, 'the same load on foot does not fire it at all');
}

// ── 4. the trigger decides WHETHER, exposure decides HOW BADLY ─────────────
// MISSIONS.md §4.1's structural claim, and the reason this is not a second
// risk system bolted beside the market's.
{
  const step = { verb: 'MOVE', triggers: ['bulk'] };
  const ctx = { units: 12 };

  const busyDay = fire(step, { ...ctx, anchor: anchor('piritori'), block: 'day' }, exposure);
  const quietHill = fire(step, { ...ctx, anchor: anchor('torkkelinmaki'), block: 'night' }, exposure);

  ok(busyDay.fired.length === 1 && quietHill.fired.length === 1,
    'the same trigger fires in both places — WHETHER does not depend on the room');
  ok(busyDay.fired[0].severity > quietHill.fired[0].severity,
    `but it costs more where there are eyes (${busyDay.fired[0].severity} vs ${quietHill.fired[0].severity})`);
}

// ── 5. only two verbs can end the block, and only unanswered ───────────────
{
  const ends = Object.entries(VERBS).filter(([, v]) => v.ends).map(([k]) => k);
  ok(ends.length === 2 && ends.includes('LOSE') && ends.includes('HURT'),
    `only LOSE and HURT end a block early (${ends.join(', ')})`);

  const tailed = { verb: 'LOSE', triggers: ['known'] };
  const caught = fire(tailed, { anchor: anchor('piritori'), grievance: 2, block: 'night' }, exposure);
  ok(caught.ends, 'a failed LOSE ends the block');

  const sentSomeoneElse = fire(tailed, { anchor: anchor('piritori'), grievance: 2, block: 'night', speaker: 'mira' }, exposure);
  ok(!sentSomeoneElse.ends, 'sending a different face answers it and the block continues');

  const talk = { verb: 'MEET', triggers: ['known'] };
  ok(!fire(talk, { anchor: anchor('piritori'), grievance: 2 }, exposure).ends, 'a MEET going badly never ends the block');
}

// ── 6. determinism ─────────────────────────────────────────────────────────
{
  const step = { verb: 'SELL', triggers: ['dry', 'bulk'] };
  const ctx = { anchor: anchor('harju'), saturation: 9, units: 10, block: 'evening' };
  const a = JSON.stringify(fire(step, ctx, exposure));
  const b = JSON.stringify(fire(step, ctx, exposure));
  ok(a === b, 'the same state fires the same triggers — nothing is rolled');
}

// ── 7. every trigger is reachable, and every one has an answer ─────────────
// A trigger nothing can satisfy is a tax; a trigger nothing can fire is dead
// content. Both have shipped in this repo before under different names.
{
  const REACH = {
    smell: { carrying: ['weed'], transport: 'public' },
    bulk: { units: 12 },
    shape: { crew: 4, armed: true, block: 'day' },
    drunk: { condition: 'drunk', block: 'day', busy: true },
    stoned: { condition: 'stoned', verb: 'MEET' },
    known: { grievance: 1 },
    dry: { verb: 'SELL', saturation: 9 },
  };
  let unreachable = 0, unanswerable = 0;
  for (const [id, t] of Object.entries(TRIGGERS)) {
    const c = REACH[id];
    if (!c || !t.when({ ...c, verb: c.verb ?? 'MOVE' })) { unreachable++; console.log('  (unreachable) ' + id); }
    if (!t.answer) unanswerable++;
  }
  ok(unreachable === 0, `every trigger can fire (${Object.keys(TRIGGERS).length} checked)`);
  ok(unanswerable === 0, 'every trigger names its answer');

  // §4.2: `shape` must not be a police problem, or the system collapses into
  // one opponent.
  ok(/grievance|remember/i.test(TRIGGERS.shape.cost), '`shape` costs standing, not police attention');
}

// ── 8. the four authored missions, run through the validator ───────────────
// The half that keeps this honest: real content, not fixtures.
{
  const missions = slice.missions ?? [];
  ok(missions.length === 4, `the slice carries ${missions.length} authored missions`);

  let withSignal = 0, withThree = 0, withSteps = 0;
  const lines = [];
  for (const m of missions) {
    const v = validate(m);
    if (m.signal_encounter_id) withSignal++;
    if (['success_effects', 'partial_effects', 'failure_effects'].every(k => (m[k] ?? []).length)) withThree++;
    if ((m.steps ?? []).length) withSteps++;
    lines.push(`  ${m.id.padEnd(30)} ${m.family.padEnd(20)} ${v.ok ? 'ok' : v.findings.filter(f => f.level === 'error').length + ' error(s)'}`);
  }
  console.log('\n' + lines.join('\n'));

  ok(withSignal === missions.length, 'every authored mission arrives through somebody (§1)');
  ok(withThree === missions.length, 'every one has three outcomes (§1)');
  // This is the finding, asserted so it cannot quietly stop being true either
  // way: today NONE of them have steps, and MISSIONS.md §6 says so.
  ok(withSteps === 0, 'and none of them have steps yet — they are errands, as §6 records');
}

console.log(`\nmissions model — ${pass} passed, ${fail} failed\n`);
process.exit(fail ? 1 : 0);
