import * as T from 'three';
import {createSession} from './session.js?v=1';
import {loadFighters,makeActor,updateActor,disposeActor} from './actors.js?v=1';
import {attackTargets,validMoveCells,coverStandingLine} from './resolver.js?v=1';
import {LANES,totalRows,parseSlotKey} from '../js/v3/grid.js?v=1';

const $=id=>document.getElementById(id),canvas=$('scene'),area=$('arena');
let session,templates,content,manifest,busy=true,action='',auto=false,angle=.65,zoom=1,sequence=0,hidden=false;
let renderer,world,camera,highlight,ray,ground,actors=new Map(),labels=new Map(),fps=0,low=false,frameCount=0,seconds=0;
const CELL=1.17,position=cell=>{const p=parseSlotKey(cell);return new T.Vector3((p.lane-(LANES-1)/2)*CELL,0,(3.5-p.depth)*CELL);};
const all=()=>session.battle.players.concat(session.battle.enemies),selected=()=>session.battle.players.find(u=>u.id===session.battle.selectedId);
const hint=text=>$('hint').textContent=text;
function activate(el,fn){let last=-1000;for(const name of ['pointerup','touchend','click'])el.addEventListener(name,e=>{if(el.disabled||name==='click'&&e.detail!==0)return;e.preventDefault();if(performance.now()-last<260)return;last=performance.now();fn();});}
function button(text,fn,attrs={}){const b=document.createElement('button');b.textContent=text;for(const [k,v] of Object.entries(attrs))b.setAttribute(k,v);activate(b,fn);return b;}
function material(color){return new T.MeshStandardMaterial({color,roughness:.94});}
function box(w,h,d,x,y,z,mat){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;world.add(m);return m;}
function buildStage(){
  world=new T.Scene();world.background=new T.Color(0x25302b);world.fog=new T.Fog(0x25302b,23,42);
  renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
  camera=new T.OrthographicCamera(-5,5,5,-5,.1,60);ray=new T.Raycaster();ground=new T.Plane(new T.Vector3(0,1,0),0);highlight=new T.Group();world.add(highlight);
  world.add(new T.HemisphereLight(0xd4e6d7,0x484536,2));
  const sun=new T.DirectionalLight(0xffdab0,2.8);sun.position.set(-4,9,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-7,right:7,top:7,bottom:-7,near:.1,far:24});sun.shadow.normalBias=.035;world.add(sun);
  const fill=new T.DirectionalLight(0xb6d8de,1.2);fill.position.set(5,5,-5);world.add(fill);
  const concrete=material(0x797b6d),edge=material(0x414a40),metal=material(0x303c36),rust=material(0x755d4b);
  box(8.5,.3,11,0,-.18,0,concrete);box(8.5,1.9,.25,0,.95,-5.5,edge);box(.25,1.9,2,-4.25,.95,-4.65,edge);
  for(let i=0;i<7;i++){box(.025,.015,10,i*1.17-3.5,.004,0,edge);}
  for(let i=0;i<9;i++)box(7,.015,.02,0,.004,i*1.17-4.68,edge);
  for(const x of [-2.7,2.7]){box(.9,1.45,.12,x,.75,-5.33,metal);box(.9,.12,.18,x,1.55,-5.22,rust);}
  for(const [cell] of session.battle.cover){const p=position(cell);box(.90,.52,.32,p.x,.26,p.z-.37,edge);box(.96,.07,.36,p.x,.55,p.z-.37,concrete);}
  // Restraint here is deliberate: scenery gets its own Dream Loop pass.
  for(const z of [-2,0,2])box(.12,.10,.8,-3.9,.06,z,rust);
  fit();new ResizeObserver(fit).observe(area);
}
function fit(){if(!renderer)return;const w=area.clientWidth,h=area.clientHeight;renderer.setSize(w,h,false);const aspect=w/h,span=Math.max(10.9,13.8/aspect)/zoom;Object.assign(camera,{left:-span*aspect/2,right:span*aspect/2,top:span/2,bottom:-span/2});camera.position.set(Math.sin(angle)*13,10,Math.cos(angle)*13);camera.lookAt(0,.55,0);camera.updateProjectionMatrix();}
function reset(mode=$('loadout').value){sequence++;auto=false;for(const a of actors.values())disposeActor(a);actors.clear();$('labels').replaceChildren();labels.clear();session=createSession(content,mode);for(const u of all()){const a=makeActor(templates.get(u.modelId),u,world);a.group.position.copy(position(u.cell));a.group.rotation.y=u.side==='player'?Math.PI:0;actors.set(u.id,a);const el=document.createElement('div');el.className='actor-label '+(u.side==='enemy'?'enemy':'');el.dataset.unit=u.id;$('labels').append(el);labels.set(u.id,el);}busy=false;action='';$('result').hidden=true;hint('Choose a fighter, then an action. One action each round.');refresh();}
function clearHighlights(){for(const o of [...highlight.children]){o.geometry.dispose();o.material.dispose();highlight.remove(o);}}
function tile(cell,color,opacity=.22){const p=position(cell),m=new T.Mesh(new T.PlaneGeometry(CELL*.9,CELL*.9),new T.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,side:T.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.copy(p).setY(.025);highlight.add(m);}
function refresh(){
  if(!session)return;const b=session.battle,u=selected(),ended=b.status!=='active',canAct=!busy&&!ended&&u?.alive&&!b.acted.includes(u.id);
  $('round').textContent='ROUND '+String(b.round).padStart(2,'0');$('phase').textContent=busy?'RESOLVING':ended?'COMPLETE':'JADE · YOUR TURN';
  const focused=document.activeElement?.dataset.unitid;$('roster').replaceChildren();
  for(const p of b.players){const el=button('',()=>select(p.id),{'data-unitid':p.id,'aria-pressed':String(p.id===u?.id)});el.innerHTML=`<span class="identity">${p.name}<small>${p.equipment==='baseball-bat'?'Bat':p.equipment==='folding-knife'?'Blade':'Handgun'} · ${b.acted.includes(p.id)?'ACTION USED':p.alive?'READY':'DOWN'}</small></span><span class="stats">HP ${p.hp}/${p.maxHp}<br>Guard ${p.guard}</span>`;el.disabled=busy||ended||!p.alive||b.acted.includes(p.id);$('roster').append(el);}
  if(focused)$('roster').querySelector(`[data-unitid="${focused}"]`)?.focus({preventScroll:true});
  for(const el of document.querySelectorAll('[data-action]')){el.disabled=!canAct||(el.dataset.action==='item'&&!u.itemIds.includes('training-bandage'));el.setAttribute('aria-pressed',String(action===el.dataset.action));}
  for(const id of ['end','talk','withdraw','auto','showcase','restart','loadout'])$(id).disabled=busy||(ended&&!['restart','loadout','showcase'].includes(id));
  $('talk').disabled=busy||ended||b.round<2; $('auto').textContent='Auto: '+(auto?'on':'off');$('auto').setAttribute('aria-pressed',String(auto));
  $('choices').replaceChildren();$('choices').hidden=!canAct||!['move','attack'].includes(action);clearHighlights();
  if(canAct&&action==='move')for(const cell of validMoveCells(b,u)){tile(cell,0x8ecbaf);const p=parseSlotKey(cell);$('choices').append(button(`${String.fromCharCode(65+p.lane)}${p.depth+1}`,()=>run('move',cell),{'data-cell':cell,'aria-label':`Move to ${String.fromCharCode(65+p.lane)}${p.depth+1}`}));}
  if(canAct&&action==='attack'){const targets=attackTargets(b,u);for(const target of b.enemies.filter(v=>v.alive)){const valid=targets.some(v=>v.id===target.id),el=button(`${target.name} · ${valid?(target.guard?'break guard':'hit condition'):'out of reach / blocked'}`,()=>run('attack',target.id),{'data-target':target.id});el.disabled=!valid;$('choices').append(el);if(valid)tile(target.cell,0xe9a38b,.30);}}
  for(const p of all()){const el=labels.get(p.id),a=actors.get(p.id);el.classList.toggle('active',p.id===u?.id);el.classList.toggle('down',!p.alive);el.innerHTML=`${p.id.includes('f02')?'F02 WIRY':'F01 HEAVY'}<small>${p.alive?`HP ${p.hp}/${p.maxHp} · G ${p.guard}`:'DOWN'}</small>`;a.ring.material.opacity=p.alive?1:.25;a.ring.material.transparent=true;}
  $('log').replaceChildren(...b.log.slice(0,12).map(s=>{const li=document.createElement('li');li.textContent=s;return li;}));
  if(ended&&!busy){$('result').hidden=false;$('result-title').textContent=({win:'JADE HOLDS THE YARD',loss:'RUST HOLDS THE YARD',withdraw:'CREW WITHDREW',partial:'TRUCE REACHED'})[b.result];$('result-text').textContent=`${b.round} rounds. ${all().filter(v=>!v.alive).length} downed. Training only: no campaign changes.`;}
}
function select(id){if(busy)return;session.command('select',id);action='';hint('Choose Attack, Move, Brace or Bandage.');refresh();}
function choose(name){if(busy||session.battle.status!=='active')return;if(['brace','item'].includes(name)){run(name);return;}action=action===name?'':name;hint(name==='move'?'Tap a green cell, or choose its coordinate below. Reposition spends this action.':'Choose a highlighted opponent. Cover and weapon lanes determine reach.');refresh();}
function tween(seconds,fn){const ticket=sequence;let elapsed=0;return new Promise(resolve=>{let last=performance.now();function tick(now){if(ticket!==sequence){resolve();return;}const dt=hidden?0:Math.min(.05,(now-last)/1000);last=now;elapsed+=dt;fn(Math.min(1,elapsed/seconds));if(elapsed<seconds)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});}
async function moveVisual(id,to){const a=actors.get(id),from=a.group.position.clone(),dest=typeof to==='string'?position(to):to;const d=dest.clone().sub(from);if(d.length()<.01)return;a.group.rotation.y=Math.atan2(d.x,d.z);a.play('walk');await tween(Math.min(1.3,Math.max(.5,d.length()*.2)),t=>a.group.position.lerpVectors(from,dest,t));a.play('idle');}
async function gesture(id,mode,duration=.75){const a=actors.get(id);a.play(mode,duration);await tween(duration,()=>{});if(mode!=='down')a.play('idle');}
function spark(at){const g=new T.Group();world.add(g);for(let i=0;i<8;i++){const o=new T.Mesh(new T.BoxGeometry(.027,.027,.027),new T.MeshBasicMaterial({color:i%2?0xd8c090:0xb7c6ae}));g.add(o);}tween(.3,t=>g.children.forEach((o,i)=>{o.position.copy(at).add(new T.Vector3(Math.sin(i*4)*t*.45,Math.sin(t*Math.PI)*.4,Math.cos(i*4)*t*.45));})).then(()=>{g.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});g.removeFromParent();});}
async function attackVisual(id,targetId){const a=actors.get(id),target=actors.get(targetId);if(!a||!target)return;const home=a.group.position.clone(),goal=target.group.position.clone(),d=goal.clone().sub(home).normalize(),ranged=a.unit.equipment.includes('handgun');a.group.rotation.y=Math.atan2(d.x,d.z);
  if(!ranged&&home.distanceTo(goal)>1.2)await moveVisual(id,goal.clone().addScaledVector(d,-.92));
  a.play(ranged?'shoot':'strike',.85);await tween(.4,()=>{});spark(goal.clone().setY(1.15));target.play('hit',.45);await tween(.45,()=>{});target.play('idle');a.play('idle');
  if(!ranged&&a.group.position.distanceTo(home)>.01)await moveVisual(id,home);
}
async function present(record){
  const {type,actor,value,before,after,events}=record;
  if(type==='move')await moveVisual(actor,value);
  else if(type==='attack')await attackVisual(actor,value);
  else if(['brace','item'].includes(type))await gesture(actor,type);
  else if(type==='talk')await Promise.all(session.battle.players.filter(u=>u.alive).map(u=>gesture(u.id,'talk')));
  else if(type==='withdraw')await Promise.all(session.battle.players.filter(u=>u.alive).map(u=>moveVisual(u.id,actors.get(u.id).group.position.clone().add(new T.Vector3(0,0,2.2)))));
  else if(['end','auto'].includes(type)&&events.length){for(const e of events){if(e.type==='move')await moveVisual(e.id,e.to);else if(e.type==='attack')await attackVisual(e.id,e.target);else await gesture(e.id,'brace');}}
  else if(type==='auto'){for(const next of after.units){const old=before.units.find(v=>v.id===next.id);if(old.cell!==next.cell)await moveVisual(next.id,next.cell);}for(const next of after.units){const old=before.units.find(v=>v.id===next.id);if(old.hp>next.hp||old.guard>next.guard)await gesture(next.id,'hit',.4);}}
  for(const next of after.units){const old=before.units.find(v=>v.id===next.id);if(old.alive&&!next.alive)await gesture(next.id,'down',.7);}
  for(const u of all()){if(!u.alive)continue;const a=actors.get(u.id);if(type!=='withdraw')a.group.position.copy(position(u.cell));a.group.rotation.y=u.side==='player'?Math.PI:0;}
}
async function run(type,value){if(busy)return;const result=session.command(type,value);if(!result.ok){hint(result.message||'That action is not available yet.');return;}busy=true;action='';refresh();await present(result.record);busy=false;hint(session.battle.log[0]);refresh();if(auto&&session.battle.status==='active')setTimeout(()=>{if(auto&&!busy)run('auto');},600);}
async function showcase(){if(busy)return;auto=false;busy=true;action='';refresh();const starts=new Map([...actors].map(([id,a])=>[id,a.group.position.clone()]));for(const mode of ['idle','walk','strike','shoot','brace','item','talk','hit','grip','down']){hint(`ACTION REHEARSAL · ${mode.toUpperCase()} · ${['idle','walk'].includes(mode)?'own-character clip':'prototype gesture'}`);for(const a of actors.values()){a.down=false;a.play(mode,1.15);}await tween(1.15,t=>{if(mode==='walk')for(const [id,a] of actors)a.group.position.copy(starts.get(id)).add(new T.Vector3(.45*Math.sin(t*Math.PI),0,0));});}reset();hint('Rehearsal complete. Fresh battle ready.');}
for(const el of document.querySelectorAll('[data-action]'))activate(el,()=>choose(el.dataset.action));
activate($('end'),()=>run('end'));activate($('talk'),()=>run('talk'));activate($('withdraw'),()=>run('withdraw'));activate($('auto'),()=>{auto=!auto;refresh();if(auto&&!busy)run('auto');});activate($('restart'),()=>reset());activate($('again'),()=>reset());activate($('showcase'),showcase);$('loadout').addEventListener('change',()=>reset());activate($('help'),()=>$('help-dialog').showModal());
activate($('download'),()=>{const blob=new Blob([JSON.stringify(session.result(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='piritori-fight-module-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
activate($('rotate'),()=>{angle+=Math.PI/4;fit();});activate($('zoomout'),()=>{zoom=Math.max(.7,zoom-.15);fit();});activate($('zoomin'),()=>{zoom=Math.min(1.7,zoom+.15);fit();});activate($('resetcam'),()=>{angle=.65;zoom=1;fit();});
function boardTap(x,y){if(busy)return;const rect=canvas.getBoundingClientRect(),p=new T.Vector2((x-rect.left)/rect.width*2-1,-(y-rect.top)/rect.height*2+1);ray.setFromCamera(p,camera);if(action==='move'){const at=new T.Vector3();if(ray.ray.intersectPlane(ground,at))run('move',`${Math.round(at.x/CELL+(LANES-1)/2)},${Math.round(3.5-at.z/CELL)}`);return;}const hit=ray.intersectObjects([...actors.values()].map(a=>a.body),true)[0];if(!hit)return;let node=hit.object;while(node&&!node.userData.unitId)node=node.parent;if(!node)return;const u=all().find(v=>v.id===node.userData.unitId);if(u.side==='player')select(u.id);else if(action==='attack')run('attack',u.id);else hint('Choose Attack first, then a highlighted opponent.');}
let down=null,lastTap=0;canvas.addEventListener('pointerdown',e=>{down={id:e.pointerId,x:e.clientX,y:e.clientY,angle};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(down&&down.id===e.pointerId&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>9){angle=down.angle+(e.clientX-down.x)*.006;fit();}});canvas.addEventListener('pointerup',e=>{if(!down)return;const tap=Math.hypot(e.clientX-down.x,e.clientY-down.y)<9;down=null;lastTap=performance.now();if(tap)boardTap(e.clientX,e.clientY);});canvas.addEventListener('pointercancel',()=>{down=null;});canvas.addEventListener('touchend',e=>{if(performance.now()-lastTap<300)return;const t=e.changedTouches[0];if(t&&!down){e.preventDefault();boardTap(t.clientX,t.clientY);}},{passive:false});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=T.MathUtils.clamp(zoom-e.deltaY*.001,.7,1.7);fit();},{passive:false});
window.addEventListener('keydown',e=>{if($('help-dialog').open)return;if(e.key==='Escape'){action='';refresh();return;}if(e.target.matches('select,input')||(e.key==='Enter'&&e.target.matches('button,a,summary')))return;const key=e.key.toLowerCase();if(key==='1'||key==='2')select(session.battle.players[Number(key)-1].id);if({a:'attack',m:'move',b:'brace',i:'item'}[key])choose({a:'attack',m:'move',b:'brace',i:'item'}[key]);if(e.key==='Enter'){e.preventDefault();run('end');}});
let padPrevious=[],padAt=0;function controller(now){const p=navigator.getGamepads?.()[0];if(!p)return;const fresh=i=>p.buttons[i]?.pressed&&!padPrevious[i];const controls=[...document.querySelectorAll('button,select,summary,a')].filter(e=>!e.disabled&&e.getClientRects().length&&!e.closest('[hidden]')&&(!$('help-dialog').open||e.closest('dialog')));if(now-padAt>170&&(fresh(13)||fresh(15)||fresh(12)||fresh(14))){const step=fresh(13)||fresh(15)?1:-1,index=controls.indexOf(document.activeElement);controls[(index+step+controls.length)%controls.length]?.focus();padAt=now;}if(fresh(0))document.activeElement?.click();if(fresh(1)){if($('help-dialog').open)$('help-dialog').close();else{action='';refresh();}}if(fresh(6)||fresh(7)){zoom=T.MathUtils.clamp(zoom+(fresh(7)?.15:-.15),.7,1.7);fit();}padPrevious=p.buttons.map(v=>v.pressed);}
document.addEventListener('visibilitychange',()=>{hidden=document.hidden;});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();sequence++;busy=true;$('loading').hidden=false;$('loading').textContent='Graphics interrupted. Reload to restore the fight.';});
let previous=performance.now();function tick(now){requestAnimationFrame(tick);const real=Math.max(0,(now-previous)/1000),dt=hidden?0:Math.min(.05,real);previous=now;if(hidden||!renderer)return;for(const a of actors.values())updateActor(a,dt);for(const u of all()){const a=actors.get(u.id),p=a.group.position.clone().add(new T.Vector3(0,a.down?.35:2.04,0)).project(camera),el=labels.get(u.id);el.style.transform=`translate(-50%,-100%) translate(${(p.x+1)*area.clientWidth/2}px,${(1-p.y)*area.clientHeight/2}px)`;}renderer.render(world,camera);controller(now);frameCount++;seconds+=real;if(seconds>2){fps=Math.round(frameCount/seconds);if(fps<22&&!low){low=true;renderer.setPixelRatio(1);renderer.shadowMap.enabled=false;}$('perf').textContent=`C.03 · ${fps} FPS · ${renderer.info.render.calls} draws${low?' · low FX':''}`;frameCount=0;seconds=0;}}
async function boot(){[content,manifest]=await Promise.all(['../../content/era1-slice-v1.json','../../art/v3/manifest.json'].map(p=>fetch(p).then(r=>{if(!r.ok)throw Error('Data failed '+r.status);return r.json();})));session=createSession(content);buildStage();templates=await loadFighters(manifest);reset();$('loading').hidden=true;requestAnimationFrame(tick);window.fightModule={snapshot:()=>session.snapshot(),metrics:()=>({fps,draws:renderer.info.render.calls,geometries:renderer.info.memory.geometries,models:actors.size,bones:[...actors.values()].map(a=>a.bones.size),busy,mode:session.mode,history:session.history.map(r=>({type:r.type,actor:r.actor,value:r.value})),finite:[...actors.values()].every(a=>[...a.bones.values()].every(b=>b.matrixWorld.elements.every(Number.isFinite)))})};}
boot().catch(e=>{$('loading').hidden=false;$('loading').textContent='Unable to load fight: '+e.message;console.error(e);});



